game:
	@echo 'building rugby game...'
	copy Begin.moon+\
	Util.moon+\
	Config.moon+\
	Vector.moon+\
	Player.moon+\
	World.moon+\
	Entity.moon+\
	Character.moon+\
	Ball.moon+\
	Stadium.moon+\
	RugbyMan.moon+\
	End.moon   build.moon