build:
	@echo 'building rugby game...'
	copy "wrapper\\begin.wren"+\
	"engine\\Util.wren"+\
	"engine\\Draw.wren"+\
	"engine\\Vector.wren"+\
	"engine\\World.wren"+\
	"engine\\Entity.wren"+\
	"engine\\Sprite.wren"+\
	"engine\\Shadow.wren"+\
	"engine\\Camera.wren"+\
	"engine\\Player.wren"+\
	"game\\Stadium.wren"+\
	"game\\Ball.wren"+\
	"game\\RugbyMan.wren"+\
	"game\\Game.wren"+\
	"wrapper\\end.wren" "build.wren"